<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KamarSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('kamar')->insert([
            [
                'id_kamar' => 1,
                'no_kamar' => '1',
                'tipe_kamar' => 'Standard',
                'harga' => 750000,
                'status' => 'Kosong',
                'id_kost' => 1,
            ],
            [
                'id_kamar' => 2,
                'no_kamar' => '2',
                'tipe_kamar' => 'Standard',
                'harga' => 750000,
                'status' => 'terisi',
                'id_kost' => 1,
            ],
            [
                'id_kamar' => 3,
                'no_kamar' => '3',
                'tipe_kamar' => 'Standard',
                'harga' => 750000,
                'status' => 'Kosong',
                'id_kost' => 1,
            ],
            [
                'id_kamar' => 4,
                'no_kamar' => '4',
                'tipe_kamar' => 'Standard',
                'harga' => 750000,
                'status' => 'terisi',
                'id_kost' => 1,
            ],
            [
                'id_kamar' => 5,
                'no_kamar' => '5',
                'tipe_kamar' => 'Standard',
                'harga' => 750000,
                'status' => 'terisi',
                'id_kost' => 1,
            ],
            [
                'id_kamar' => 6,
                'no_kamar' => '6',
                'tipe_kamar' => 'Standard',
                'harga' => 750000,
                'status' => 'terisi',
                'id_kost' => 1,
            ],
            [
                'id_kamar' => 7,
                'no_kamar' => '7',
                'tipe_kamar' => 'Standard',
                'harga' => 750000,
                'status' => 'Kosong',
                'id_kost' => 1,
            ],
            [
                'id_kamar' => 8,
                'no_kamar' => '8',
                'tipe_kamar' => 'Standard',
                'harga' => 750000,
                'status' => 'terisi',
                'id_kost' => 1,
            ],
            [
                'id_kamar' => 9,
                'no_kamar' => '9',
                'tipe_kamar' => 'Standard',
                'harga' => 750000,
                'status' => 'Kosong',
                'id_kost' => 1,
            ],
            [
                'id_kamar' => 10,
                'no_kamar' => '10',
                'tipe_kamar' => 'Standard',
                'harga' => 750000,
                'status' => 'Kosong',
                'id_kost' => 1,
            ],
            [
                'id_kamar' => 11,
                'no_kamar' => '11',
                'tipe_kamar' => 'Standard',
                'harga' => 750000,
                'status' => 'Kosong',
                'id_kost' => 1,
            ],
            [
                'id_kamar' => 12,
                'no_kamar' => '12',
                'tipe_kamar' => 'Standard',
                'harga' => 750000,
                'status' => 'terisi',
                'id_kost' => 1,
            ],
            [
                'id_kamar' => 13,
                'no_kamar' => '13',
                'tipe_kamar' => 'Standard',
                'harga' => 750000,
                'status' => 'terisi',
                'id_kost' => 1,
            ],
            [
                'id_kamar' => 14,
                'no_kamar' => '14',
                'tipe_kamar' => 'Standard',
                'harga' => 750000,
                'status' => 'Kosong',
                'id_kost' => 1,
            ],
            [
                'id_kamar' => 15,
                'no_kamar' => '15',
                'tipe_kamar' => 'Standard',
                'harga' => 750000,
                'status' => 'Kosong',
                'id_kost' => 1,
            ],
            [
                'id_kamar' => 16,
                'no_kamar' => '16',
                'tipe_kamar' => 'Standard',
                'harga' => 750000,
                'status' => 'Kosong',
                'id_kost' => 1,
            ],
            [
                'id_kamar' => 17,
                'no_kamar' => '17',
                'tipe_kamar' => 'Standard',
                'harga' => 750000,
                'status' => 'Kosong',
                'id_kost' => 1,
            ],
            [
                'id_kamar' => 18,
                'no_kamar' => '18',
                'tipe_kamar' => 'Standard',
                'harga' => 750000,
                'status' => 'Kosong',
                'id_kost' => 1,
            ],
            [
                'id_kamar' => 19,
                'no_kamar' => '19',
                'tipe_kamar' => 'Standard',
                'harga' => 750000,
                'status' => 'Kosong',
                'id_kost' => 1,
            ],
            [
                'id_kamar' => 20,
                'no_kamar' => '20',
                'tipe_kamar' => 'Standard',
                'harga' => 750000,
                'status' => 'Kosong',
                'id_kost' => 1,
            ],
            [
                'id_kamar' => 21,
                'no_kamar' => '21',
                'tipe_kamar' => 'Standard',
                'harga' => 750000,
                'status' => 'Kosong',
                'id_kost' => 1,
            ],
            [
                'id_kamar' => 22,
                'no_kamar' => '22',
                'tipe_kamar' => 'Standard',
                'harga' => 750000,
                'status' => 'terisi',
                'id_kost' => 1,
            ],
            [
                'id_kamar' => 23,
                'no_kamar' => '23',
                'tipe_kamar' => 'Standard',
                'harga' => 750000,
                'status' => 'terisi',
                'id_kost' => 1,
            ],
        ]);
    }
}